spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sqldemo?serverTimezone=UTC
    username: demo
    password: 123
    type: com.mchange.v2.c3p0.ComboPooledDataSource
mybatis:
  mapper-locations: classpath:mybatis/mappers/*.xml
  type-aliases-package: com.pgq.**.entity